### ISSUE TITLE
View data, Run Report and PDF

### ISSUE THREAD

**Issue by denhamgithub** [soliforte/kismetreportgen#1]
Is your report generator supposed to display a list of BSSID & SSID's?  When I accessed the suggested http://localhost:2501/plugin/reportgen/, it contained no data, just column labels. I waited five minutes but still no data.
I next opened another browser window localhost:2501 and then chose a BSSID for an AP.  And pasted into the SSID box and chose Run Report.  I waited another five minutes but there was no indication that a report had been generated.  I then chose Download PDF and saved the Wifi-report.pdf.  When I opened the PDF with two different PDF readers, the report was blank.  
It only showed a list of columns with a blue color and no data.
What could I being doing wrong?
Dennis Eckert

**Comment by soliforte** [comment]
Dennis,
I just downloaded and installed the plugin on the most recent version of kismet and it ran without any issues.

With the kismet server running, I navigated to /plugin/reportgen/ 
Typed in an SSID, clicked "Add" and then clicked "Run Report". It populated the table with a list of AP's (SSID, Nickname, BSSID, Encryption, MAC, Type, Client Count, Signal, Channel).

You may be typing the SSID incorrectly, or perhaps no data has been collected of the ssid yet?

**Comment by soliforte** [comment]
I also just noticed that you said "pasted a BSSID into the SSID box".

**Comment by denhamgithub** [comment]
Thank you for catching this. I recently had serious next surgery and them not yet to the point where I can get on a PC. I am using my kindle with voice to text to respond.So I hope I will gain access to my PC and rerun your software and fix my error.

Thanks for your patience.
Dennis E.

On January 14, 2020, at 10:25 PM, Soli Forte <notifications@github.com> wrote:

I also just noticed that you said "pasted a BSSID into the SSID box".

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.￼

[ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/soliforte/kismetreportgen/issues/1?email_source=notifications">https://github.com/soliforte/kismetreportgen/issues/1?email_source=notifications</a>\u0026email_token=AF53SIP2FG6YWOE7TFEN34DQ52T45A5CNFSM4HMLOMY2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEI7GSHA#issuecomment-574515484", "url": "<a href="https://github.com/soliforte/kismetreportgen/issues/1?email_source=notifications">https://github.com/soliforte/kismetreportgen/issues/1?email_source=notifications</a>\u0026email_token=AF53SIP2FG6YWOE7TFEN34DQ52T45A5CNFSM4HMLOMY2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEI7GSHA#issuecomment-574515484", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]
