### ISSUE TITLE
Updated Instruction

### ISSUE THREAD

**Issue by quarinteen** [soliforte/kismetreportgen#4]
Hello I was wondering if possible if you could elaborate on the installation process? The default data directory does not appear to be set to /usr/local on a default latest install of arm64 kali on raspberry pi. I attempted to install this in both kismet folders and neither worked. Thank you I look forward to using this plugin when I am able to install it.

**Comment by quarinteen** [comment]
I just wanted to update this. After discussing this with the kismet team it seems the best way to install this is by using "make userinstall". There is an issue with the way Kismet is being installed on the raspberry pi. Kismet by default on a fresh kali install with a fresh kismet install is looking for  system wide plugin directory in /usr/lib/aarch64-linux-gnu/kismet/

**Comment by soliforte** [comment]
I only use Ubuntu and macOS, because every other version of linux has unnecessary hoops to jump through to make basic stuff work, so I don't really have any advice for working with anything besides Ubuntu and macOS.
